Obligatorio2/Obligatorio2/Controllers/ABMController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Obligatorio2Clases;

namespace Obligatorio2.Controllers
{
    public class ABMController : Controller
    {
        // GET: ABM


        public ActionResult Index() {

             if (Session["Vendedor"] != null)
            {

                ViewBag.Estado = "Hay un vendedor logueado,por favor cierre sesion para poder acceder a las opciones";
                return Redirect("~/Login/Cerrarsesion");
            }

            return View();
        }
        public ActionResult ModificarClientes(string cliente, string apellido, string direccion, string telefono)
        {

            if (Session["Vendedor"] != null)
            {

                ViewBag.Estado = "Hay un vendedor logueado,por favor cierre sesion para poder acceder a las opciones";
                return Redirect("~/Login/Cerrarsesion");
            }
            else
            {

                if (direccion != "" && apellido != "" && telefono != "")
                {

                    Sistema.Instancia.CambiarDatos(cliente, apellido, direccion, telefono);
                    ViewBag.Estado = "Cambio los datos correctamente";
                }
                else
                {
                    ViewBag.Estado = "Hay campos vacios,Verifique!!";
                }

                return View("ModificarClientes");

            }
        }

        public ActionResult AltaClientes(string nombre, string apellido, string documento, string direccion, string telefono)
        {
            if (Session["Vendedor"] != null)
            {

                ViewBag.Estado = "Hay un vendedor logueado,por favor cierre sesion para poder acceder a las opciones";
                return Redirect("~/Login/Cerrarsesion");
            }
            else
            {

                if (nombre != "" && apellido != "" && documento != "" && direccion != "" && telefono != "" && nombre != null && apellido != null && documento != null && direccion != null && telefono != null)
                {

                    ViewBag.Estado= Sistema.Instancia.AltaClientes(nombre, apellido, documento, direccion, telefono);

                }

                else
                {
                    ViewBag.Estado = "Hay campos vacios,Verifique!!";

                }
            }
            return View("AltaClientes");
        }

        public ActionResult BajaClientes(string cliente) {
            if (Session["Vendedor"] != null)
            {
                ViewBag.Estado = "Hay un vendedor logueado,por favor cierre sesion para poder acceder a las opciones";
                return Redirect("~/Login/Cerrarsesion");
            }
            ViewBag.Estado= Sistema.Instancia.EliminarClientes(cliente);

            return View("BajaClientes");

        }

    }
}

Obligatorio2/Obligatorio2/Controllers/FiltroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Obligatorio2Clases;

namespace Obligatorio2.Controllers
{
    public class FiltroController : Controller
    {
        // GET: Filtro
        public ActionResult Index()
       {
            if (ViewBag.cliente == null)
            {
                ViewBag.cliente = new List<Cliente>();
            }
            if (ViewBag.fechaI == null || ViewBag.fechaF == null)
            {
                return View("MostrarDatos");
            }
            return View("MostrarDatos");
        }

        public ActionResult MostrarDatos(DateTime ? FechaI,DateTime ?FechaF) {

            if (ViewBag.cliente == null) {
                ViewBag.cliente = new List<Cliente>();
            }
            if (FechaI != null && FechaF != null)
            {
                if (FechaI <= FechaF)
                {
                  
                    ViewBag.cliente = Sistema.Instancia.DevolverComprasPorFecha((DateTime)FechaI,(DateTime) FechaF);
                    ViewBag.Estado = "La busqueda a finalizado con los siguientes resultados:";

                }
                else {
                    ViewBag.Estado = "La fecha inicial debe ser menor a la fecha final!";
                   
                }


            }
            else {
                ViewBag.Estado = "Ingreso Fechas vacias";

            }
           
           
            return View("MostrarDatos");
        }
    }
}

Obligatorio2/Obligatorio2/Controllers/VentaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Obligatorio2Clases;

namespace Obligatorio2.Controllers
{
    public class VentaController : Controller
    {
        // GET: Venta
        public ActionResult Ventas()
        {
            if (ViewBag.apartamentos == null) {
            ViewBag.apartamentos = new List<Apartamento>();
            }
            if (Session["Vendedor"] == null) {
                ViewBag.Estado = "Debe iniciar sesion,antes de realizar una compra";
                return Redirect("~/Login/Login");
                

            }
            return View();
        }


        public ActionResult MostrarApartamentos(string edificio)
        {

            ViewBag.apartamentos = Sistema.Instancia.DevolverAptos(edificio);
            ViewBag.edificio = edificio;
            return View("Ventas");
        
    }

        public ActionResult ComprarApto(string cliente, string edificio,string apartamentos, DateTime ? fecha)
        {
            ViewBag.Cliente = cliente;
            string NombreUsuario = Session["Vendedor"].ToString();

            if (cliente != "" && edificio != "" && apartamentos != "" && fecha != null) {
                Sistema.Instancia.ComprarAptos(NombreUsuario, Convert.ToDateTime(fecha), cliente, edificio, apartamentos);
                ViewBag.apartamentos = new List<Apartamento>();
                ViewBag.Estado = "Se compro un Apartamento con exito!";
            }
            else {
                ViewBag.apartamentos = new List<Apartamento>();
                ViewBag.Estado = "Hay campos vacios,por favor seleccione una opcion!";

            }
            return View("Ventas");
        }
    }
}

Obligatorio2/Obligatorio2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Vender Apto", "Ventas", "Venta", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Ventas", "MostrarDatos", "Vendedor", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Alta Clientes", "AltaClientes", "ABM", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Modificar Clientes", "ModificarClientes", "ABM", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Baja Clientes", "BajaClientes", "ABM", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Filtro CLientes", "Index", "Filtro", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Login", "Login", "Login", new { area = "" }, new { @class = "navbar-brand" })
                @Html.ActionLink("Cerrar Sesion", "Cerrarsesion", "Login", new { area = "" }, new { @class = "navbar-brand" })


            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>